version: "3.9"

services:
  gateway:
    image: ${gateway_image}
    container_name: textflow-gateway
    restart: unless-stopped
    depends_on:
      - react
      - mlflow
      - dagster
    ports:
      - "${gateway_port}:80"
    volumes:
      - /opt/textflow/gateway/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ${perma_htpasswd_host_path}:/etc/nginx/conf.d/.htpasswd:ro

  react:
    image: ${react_image}
    container_name: textflow-react
    restart: unless-stopped
    expose:
      - "${react_port}"
    environment:
      PORT: "${react_port}"

  mlflow:
    image: ${mlflow_image}
    container_name: textflow-mlflow
    restart: unless-stopped
    expose:
      - "${mlflow_port}"
    environment:
      MLFLOW_HOST: "0.0.0.0"
      MLFLOW_PORT: "${mlflow_port}"
      MLFLOW_DB_PATH: "/app/db/mlflow.db"
      MLFLOW_BACKEND_STORE_URI: "sqlite:////app/db/mlflow.db"
      MLFLOW_ARTIFACT_ROOT: "/app/artifacts"
      MLFLOW_ARTIFACTS_DESTINATION: "gs://${mlflow_bucket}"
      MLFLOW_DEFAULT_ARTIFACT_ROOT: "gs://${mlflow_bucket}"
    volumes:
      - ${perma_db_host_path}:/app/db
      - ${perma_artifacts_host_path}:/app/artifacts
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:${mlflow_port}/api/2.0/mlflow/registered-models/list || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  dagster:
    image: ${dagster_image}
    container_name: textflow-dagster
    restart: unless-stopped
    expose:
      - "${dagster_port}"
    environment:
      DAGSTER_HOME: "/opt/dagster/dagster_home"
      DAGSTER_PORT: "${dagster_port}"
      DAGSTER_MODULE: "pipeline.definitions"
      DAGSTER_PATH_PREFIX: "/dagster"
      GPU_RUNNER_DOCKER_URL: "${gpu_runner_docker_url}"
      DAGSTER_JOB_IMAGE: "${dagster_job_image}"
      DAGSTER_DATASETS_DIR: "${dagster_datasets_dir}"
    volumes:
      - ${perma_dagster_home_host_path}:/opt/dagster/dagster_home
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:${dagster_port}/server_info || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
